language: python

notifications:
  email:
    - louis29418401@gmail.com

os:
  - linux

python:
  - "3.6"

install:
  - cd src/code2graph
  - pip install -r requirements.txt
  - pip install 'pytest>=3.6'
  - pip install pytest-cov coverage coveralls

script:
  - cd script
  - python script_run_lightweight_method.py -opt 3 -ipt ..\core\test\fashion_mnist
